---
- name: Get apt key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Add apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: nginx
  loop:
    - deb https://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx
    - deb-src https://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx

- name: Set nginx user
  set_fact:
    nginx_user: www-data
