---
- name: Install package
  package:
    name: certbot
    state: present

- name: Generate config
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    mode: 0644

- name: Get cert
  command: certbot certonly -c /etc/letsencrypt/cli.ini
  register: certbot
  changed_when: "certbot.rc != 0"

- name: Add cron
  cron:
    name: "renew cert"
    minute: "52"
    hour: "0,12"
    user: root
    job: "certbot renew -q -c /etc/letsencrypt/cli.ini"
